# Generated by Django 5.2 on 2025-05-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='fullname',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
