# Generated by Django 5.2 on 2025-04-17 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_remove_parents_created_remove_parents_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ManyToManyField(related_name='get_student_course', to='user_auth.course'),
        ),
        migrations.AlterField(
            model_name='day',
            name='descriptions',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='descriptions',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_line',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tabletype',
            name='descriptions',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='course',
            field=models.ManyToManyField(related_name='get_teacher_course', to='user_auth.course'),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ed', models.DateField(auto_now_add=True)),
                ('updated_ed', models.DateField(auto_now=True)),
                ('title', models.CharField(max_length=25, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('descriptions', models.CharField(blank=True, max_length=400, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='course', to='user_auth.course')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.table')),
                ('teacher', models.ManyToManyField(related_name='get_teacher', to='user_auth.teacher')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.group')),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ManyToManyField(related_name='get_group', to='user_auth.group'),
        ),
        migrations.DeleteModel(
            name='GroupStudent',
        ),
    ]
