# Generated by Django 5.2 on 2025-04-17 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_student_course_alter_day_descriptions_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Day',
        ),
    ]
