# Generated by Django 5.2 on 2025-04-18 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0007_alter_attendance_group_alter_attendance_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='student',
        ),
    ]
