# Generated by Django 5.2 on 2025-04-22 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0011_alter_attendance_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendance',
            name='status',
            field=models.CharField(choices=[('bor', 'Bor'), ("yo'q", "Yo'q"), ('kechikkan', 'Kechikkan'), ('sababli', 'Sabali')], max_length=10),
        ),
        migrations.CreateModel(
            name='TeacherAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('bor', 'Bor'), ("yo'q", "Yo'q"), ('kechikkan', 'Kechikkan'), ('sababli', 'Sabali')], max_length=10)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_attendances', to='user_auth.attendance')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.teacher')),
            ],
        ),
    ]
