# Generated by Django 5.2 on 2025-04-23 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0012_alter_studentattendance_status_teacherattendance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topics',
            new_name='Lesson',
        ),
        migrations.RenameField(
            model_name='grouphomework',
            old_name='topic',
            new_name='lesson',
        ),
        migrations.RemoveField(
            model_name='tabletype',
            name='created_ed',
        ),
        migrations.RemoveField(
            model_name='tabletype',
            name='updated_ed',
        ),
    ]
