# Generated by Django 5.2 on 2025-04-25 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0014_month_paymenttype_payment_delete_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ManyToManyField(related_name='students', to='user_auth.group'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL),
        ),
    ]
