from .teacher_serializers import *
from .login_serializers import *
from .lesson_serializer import *
from .homework_serializer import *
from .group_serializer import *
from .payments_serializer import *
from .statistics_serializer import *
from .table_serializer import *
from .student_serilalizer import *