from .login_view import *
from .teacher_view import *
from .homework_view import *
from .payments_view import *
from .student_view import *
from .group_view import *
from .lesson_view import *
from .statistics_view import *
from .table_view import *
from .user_crud_view import *